/:
  controller: Auth
  action: login

/login:
  controller: Auth
  action: login

/dashboard:
  controller: Auth
  action: dashboard

/register:
  controller: Auth
  action: register

/password-reset:
  controller: Auth
  action: passwordReset

/reset-password:
  controller: Auth
  action: resetPasswordForm

/logout:
  controller: Auth
  action: logout

/verify-email:
  controller: Auth
  action: verifyEmail

/check-password:
  controller: Auth
  action: checkPassword

/debug-db:
  controller: Auth
  action: debugDb

/contact:
  controller: Base
  action: contact

/mon-super-portfolio:
  controller: Base
  action: portfolio
